In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


from sklearn.impute import SimpleImputer, KNNImputer

# For Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score



from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV, LeaveOneOut, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split


from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
# For Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

# Metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_absolute_error, precision_score, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [5]:
df = pd.read_csv("H:\\MY\\Computer Science\\Python Codes\\ML Pipeline\\Final Data of Drug Dataset.csv")
df

     Unnamed: 0  Age Sex      BP Cholesterol  Na_to_K   Drug
0             0   23   F    HIGH        HIGH   25.355  drugY
1             1   47   M     LOW        HIGH   13.093  drugC
2             2   47   M     LOW        HIGH   10.114  drugC
3             3   28   F  NORMAL        HIGH    7.798  drugX
4             4   61   F     LOW        HIGH   18.043  drugY
..          ...  ...  ..     ...         ...      ...    ...
195         195   56   F     LOW        HIGH   11.567  drugC
196         196   16   M     LOW        HIGH   12.006  drugC
197         197   52   M  NORMAL        HIGH    9.894  drugX
198         198   23   M  NORMAL      NORMAL   14.020  drugX
199         199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 7 columns]

In [6]:
df.drop(columns=["Unnamed: 0"], inplace=True)
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [9]:
le = LabelEncoder()
df["BP"] = ohe.fit_transform(df["BP"])

In [10]:
le = LabelEncoder()
df["Cholesterol"] = ohe.fit_transform(df["Cholesterol"])

In [11]:
le = LabelEncoder()
df["Drug"] = ohe.fit_transform(df["Drug"])

In [15]:
le = LabelEncoder()
df["Sex"] = ohe.fit_transform(df["Sex"])

In [12]:
df["Drug"].unique()

array([4, 2, 3, 0, 1])

In [16]:
df

     Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   0            0   25.355     4
1     47    1   1            0   13.093     2
2     47    1   1            0   10.114     2
3     28    0   2            0    7.798     3
4     61    0   1            0   18.043     4
..   ...  ...  ..          ...      ...   ...
195   56    0   1            0   11.567     2
196   16    1   1            0   12.006     2
197   52    1   2            0    9.894     3
198   23    1   2            1   14.020     3
199   40    0   1            1   11.349     3

[200 rows x 6 columns]

In [44]:
X = df.drop("Drug", axis=1)
y = df["Drug"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [45]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [46]:
bagging_model = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=17)
bagging_model.fit(X_train, y_train)
print(" ")
# Perform cross-validation
validation = cross_val_score(bagging_model, X=X, y=y, cv=7, scoring='accuracy')

#print("Score of each fold: ", validation)
#print("Mean Score: ", validation.mean())
#print("Standard Deviation: ", validation.std())
print(" ")
y_pred_bag = bagging_model.predict(X_test)
bag_acc = accuracy_score(y_test, y_pred_bag)
print('Bagging Accuracy', accuracy_score(y_test, y_pred_bag))
print(" ")
print('Bagging Accuracy', classification_report(y_test, y_pred_bag))
print("----------------------")

Bagging Accuracy 0.975

Bagging Accuracy               precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.67      0.80         3
           2       1.00      1.00      1.00         3
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        18

    accuracy                           0.97        40
   macro avg       0.97      0.93      0.94        40
weighted avg       0.98      0.97      0.97        40

----------------------

In [47]:
boosting_model = AdaBoostClassifier(n_estimators=18)
boosting_model.fit(X_train, y_train)
print(" ")
validation = cross_val_score(boosting_model, X=X, y=y, cv=7, scoring='accuracy')

#print("Score of each fold: ", validation)
#print("Mean Score: ", validation.mean())
#print("Standard Deviation: ", validation.std())
print("")
y_pred_boost = boosting_model.predict(X_test)
boost_acc = accuracy_score(y_test, y_pred_boost)
print('Boosting Accuracy', accuracy_score(y_test, y_pred_boost))
print(" ")
print('Boosting Accuracy', classification_report(y_test, y_pred_boost))
print("----------------------")

Boosting Accuracy 0.85

Boosting Accuracy               precision    recall  f1-score   support

           0       0.62      1.00      0.77         5
           1       0.00      0.00      0.00         3
           2       0.00      0.00      0.00         3
           3       0.79      1.00      0.88        11
           4       1.00      1.00      1.00        18

    accuracy                           0.85        40
   macro avg       0.48      0.60      0.53        40
weighted avg       0.74      0.85      0.79        40

----------------------

c:\Users\AICOM4\anaconda3\envs\ai_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\AICOM4\anaconda3\envs\ai_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\AICOM4\anaconda3\envs\ai_env\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [48]:
## define Base Models
base_models = [
    ('tree', DecisionTreeClassifier()),
    ('svm', SVC(probability=True)),
    ('ADA', AdaBoostClassifier())
]

stacking_model = StackingClassifier(estimators=base_models, final_estimator=LogisticRegression())
stacking_model.fit(X_train, y_train)
print(" ")
validation = cross_val_score(stacking_model, X=X, y=y, cv=7, scoring='accuracy')

print("Score of each fold: ", validation)
print("Mean Score: ", validation.mean())
print("Standard Deviation: ", validation.std())
print(" ")
y_pred_stack = stacking_model.predict(X_test)
stack_acc = accuracy_score(y_test, y_pred_stack)
print('Stacking Accuracy', accuracy_score(y_test, y_pred_stack))
print(" ")
print('Stacking Accuracy', classification_report(y_test, y_pred_stack))
print("----------------------")

Score of each fold:  [1.         1.         1.         1.         0.96428571 0.96428571
 1.        ]
Mean Score:  0.9897959183673469
Standard Deviation:  0.016134069694736623

Stacking Accuracy 0.975

Stacking Accuracy               precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.67      0.80         3
           2       1.00      1.00      1.00         3
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        18

    accuracy                           0.97        40
   macro avg       0.97      0.93      0.94        40
weighted avg       0.98      0.97      0.97        40

----------------------

In [49]:
print('Bagging Accuracy', bag_acc)
print('Boosting Accuracy', boost_acc)
print('Stacking Accuracy', stack_acc)

Bagging Accuracy 0.975
Boosting Accuracy 0.85
Stacking Accuracy 0.975

In [51]:
from joblib import dump, load

# Save the model
dump(boosting_model, "Drug Model.joblib")

['Drug Model.joblib']