In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


from sklearn.impute import SimpleImputer, KNNImputer

# For Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score



from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV, LeaveOneOut, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split


from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
# For Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

# Metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_absolute_error, precision_score, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [21]:
df = pd.read_csv("H:\\MY\\Computer Science\\Python Codes\\ML Pipeline\\Final Data of Social Media Ads Dataset.csv")
df

     Unnamed: 0  Gender        Age  EstimatedSalary      Purchased
0             0    Male  19.000000     69987.373737  Not Purchased
1             1    Male  37.667513     20000.000000  Not Purchased
2             2    Male  26.000000     43000.000000  Not Purchased
3             3  Female  37.667513     57000.000000  Not Purchased
4             4    Male  19.000000     76000.000000  Not Purchased
..          ...     ...        ...              ...            ...
395         395  Female  46.000000     41000.000000      Purchased
396         396    Male  51.000000     23000.000000      Purchased
397         397  Female  50.000000     20000.000000      Purchased
398         398    Male  36.000000     33000.000000  Not Purchased
399         399  Female  49.000000     36000.000000      Purchased

[400 rows x 5 columns]

In [22]:
df.drop(columns=["Unnamed: 0"], inplace=True)
df

     Gender        Age  EstimatedSalary      Purchased
0      Male  19.000000     69987.373737  Not Purchased
1      Male  37.667513     20000.000000  Not Purchased
2      Male  26.000000     43000.000000  Not Purchased
3    Female  37.667513     57000.000000  Not Purchased
4      Male  19.000000     76000.000000  Not Purchased
..      ...        ...              ...            ...
395  Female  46.000000     41000.000000      Purchased
396    Male  51.000000     23000.000000      Purchased
397  Female  50.000000     20000.000000      Purchased
398    Male  36.000000     33000.000000  Not Purchased
399  Female  49.000000     36000.000000      Purchased

[400 rows x 4 columns]

In [23]:
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])

In [24]:
le = LabelEncoder()
df["Purchased"] = le.fit_transform(df["Purchased"])

In [25]:
df

     Gender        Age  EstimatedSalary  Purchased
0         1  19.000000     69987.373737          0
1         1  37.667513     20000.000000          0
2         1  26.000000     43000.000000          0
3         0  37.667513     57000.000000          0
4         1  19.000000     76000.000000          0
..      ...        ...              ...        ...
395       0  46.000000     41000.000000          1
396       1  51.000000     23000.000000          1
397       0  50.000000     20000.000000          1
398       1  36.000000     33000.000000          0
399       0  49.000000     36000.000000          1

[400 rows x 4 columns]

In [26]:
df["Gender"].unique()

array([1, 0])

In [27]:
df["Purchased"].unique()

array([0, 1])

In [28]:
X = df.drop("Purchased", axis=1)
y = df["Purchased"]

X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.2, random_state=42)

import numpy as np

# Convert to numeric if possible
X_train = np.array(X_train, dtype=np.float32)
X_test  = np.array(X_test, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)
y_test  = np.array(y_test, dtype=np.float32)

In [29]:
model = models.Sequential([
    
    layers.Dense(512, activation='relu', input_shape=(3,)),
    layers.Dense(256, activation='relu'),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='linear'),
])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_21 (Dense)            (None, 512)               2048

 dense_22 (Dense)            (None, 256)               131328

 dense_23 (Dense)            (None, 128)               32896

 dense_24 (Dense)            (None, 64)                8256

 dense_25 (Dense)            (None, 32)                2080

 dense_26 (Dense)            (None, 16)                528

 dense_27 (Dense)            (None, 1)                 17

=================================================================
Total params: 177,153
Trainable params: 177,153
Non-trainable params: 0
_________________________________________________________________

In [30]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [31]:
history= model.fit(X_train, y_train, epochs= 30,
                 validation_data=(X_test, y_test))

Epoch 1/30

c:\Users\AICOM4\anaconda3\envs\ai_env\lib\site-packages\tensorflow\python\util\dispatch.py:1176: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(32, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)

 9/10 [==========================>...] - ETA: 0s - loss: 4.3048e-08 - accuracy: 0.6389

c:\Users\AICOM4\anaconda3\envs\ai_env\lib\site-packages\tensorflow\python\util\dispatch.py:1176: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return dispatch_target(*args, **kwargs)

10/10 [==============================] - 4s 79ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 2/30
10/10 [==============================] - 0s 17ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 3/30
10/10 [==============================] - 0s 18ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 4/30
10/10 [==============================] - 0s 18ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 5/30
10/10 [==============================] - 0s 19ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 6/30
10/10 [==============================] - 0s 16ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 7/30
10/10 [==============================] - 0s 13ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 8/30
10/10 [==============================] - 0s 13ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 9/30
10/10 [==============================] - 0s 13ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 10/30
10/10 [==============================] - 0s 12ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 11/30
10/10 [==============================] - 0s 12ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 12/30
10/10 [==============================] - 0s 13ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 13/30
10/10 [==============================] - 0s 15ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 14/30
10/10 [==============================] - 0s 17ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 15/30
10/10 [==============================] - 0s 13ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 16/30
10/10 [==============================] - 0s 12ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 17/30
10/10 [==============================] - 0s 12ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 18/30
10/10 [==============================] - 0s 13ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 19/30
10/10 [==============================] - 0s 13ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 20/30
10/10 [==============================] - 0s 12ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 21/30
10/10 [==============================] - 0s 12ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 22/30
10/10 [==============================] - 0s 15ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 23/30
10/10 [==============================] - 0s 15ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 24/30
10/10 [==============================] - 0s 14ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 25/30
10/10 [==============================] - 0s 12ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 26/30
10/10 [==============================] - 0s 12ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 27/30
10/10 [==============================] - 0s 13ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 28/30
10/10 [==============================] - 0s 14ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 29/30
10/10 [==============================] - 0s 18ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500
Epoch 30/30
10/10 [==============================] - 0s 18ms/step - loss: 4.2841e-08 - accuracy: 0.6406 - val_loss: 4.1723e-08 - val_accuracy: 0.6500

In [32]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(f'\nTest accuracy: {test_acc}')

3/3 - 0s - loss: 4.1723e-08 - accuracy: 0.6500 - 89ms/epoch - 30ms/step

Test accuracy: 0.6499999761581421

In [33]:
(test_acc/1)*100

64.99999761581421

In [35]:
model.save("Social Media Ads Model.H5")

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: Social Media Ads Model.H5\assets

INFO:tensorflow:Assets written to: Social Media Ads Model.H5\assets